### PR TITLE
Updated code to use graph object to collect data

### LINKED ISSUE #1: Suggestion to use the graph object to collect data
https://github.com/culturecreates/artsdata-planet-scenesfrancophones/blob/4c79a94ad2a0a7fb2deb4db09aa3a9259e86367b/main.rb#L38C3-L47C6

In the code below, you can use the graph object to collect data.

```
  entity_urls.each do |entity|
    graph = RDF::Graph.new
    begin
      graph << RDF::Graph.load(entity)
      json_ld_data = graph.dump(:jsonld)
      entity_data << JSON.parse(json_ld_data)
    rescue StandardError => e
      puts "Error loading RDF from #{entity}: #{e.message}"
    end
  end
```
can become
```
  entity_urls.each do |entity|
    begin
      graph << RDF::Graph.load(entity)
    rescue StandardError => e
      puts "Error loading RDF from #{entity}: #{e.message}"
    end
  end
```
and be sure to place  `graph = RDF::Graph.new` outside the main loop.  You don't need your `entity_data` variable. And at the end you can dump using` graph.dump(:jsonld)`.

### PR DESCRIPTION
**Pull request by dev-aravind**

### CODE REVIEW

**Review by saumier — CHANGES_REQUESTED** [review]
Take a look at the demo.rb file I added. Try to use graph to collect data.

**Comment by saumier** [comment]
@dev-aravind pleas look at my review changes in your pull request so I can review again on Wednesday.

**Comment by dev-aravind** [comment]
image
This is the jsonld data generated using the demo.rb file. Is this the correct format? There is no separation between the data of the 3 events.

**Comment by saumier** [comment]
@dev-aravind Yes. The data is a graph. The picture of the graph doesn't tell me much, so I included the json-ld dump file in the repo which I dumped using `File.write('dump.jsonld', graph.dump(:jsonld))`.  Check it out in the main branch. The idea is that the graph contains triples (basically a table with 3 columns). Each event has its own URI (first column). The data has a separation between events.  I have some examples of querying the graph of 3 events in demo.rb. Each event has a name property (second column) and name value (third column). We can load the graphs of all the events, people, organizations into Artsdata and then do some SPARQLs on the data after it is loaded into Artsdata.  If you can generate a dump of the graph and save it in Github with a workflow then I can show you how to do the last step of sending the data to Artsdata.

**Comment by dev-aravind** [comment]
@saumier The code is updated and I also added a new sample workflow file to fetch the data. Let me know if you need any changes.

**Review by saumier — APPROVED** [review]

**Pull request merged**
